### ISSUE TITLE
bug(html): “end_with_newline” option doesn't work

### ISSUE THREAD

**Issue by Kristinita** [beautifier/js-beautify#1375]
### 1. Summary

[**`"end_with_newline": true` option**](https://github.com/beautify-web/js-beautify#options) doesn't work in `.jsbeautifyrc` file. js-beautify delete final newline.

### 2. Environment

+ Operating systems:
    + Windows 10 Enterprise LTSB 64-bit EN (local),
    + Ubuntu 14.04.5 LTS (Travis CI).
+ Node.js 9.11.1,
+ npm 5.8.0,
+ js-beautify 1.7.5,
+ eclint (tool, that check [**EditorConfig**](http://editorconfig.org/) settings) 2.6.0.

### 3. Configuration

[**Example configuration**](https://github.com/Kristinita/SashaGruntDebugging/tree/SashaJsBeautify) in `SashaJsBeautify` branch of my demo repository:

`.jsbeautifyrc` file:

```json
{
    "indent_with_tabs": true,
    "end_with_newline": true
}

```

`SashaJsBeautify.html`:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sasha title</title>
</head>
<body>
    Example body text
</body>
</html>

```

`.editorconfig`:

```toml
[*]
indent_style = tab
insert_final_newline = true

```

### 4. Steps to reproduce

    js-beautify -r SashaJsBeautify.html

    eclint check SashaJsBeautify.html

### 5. Actual behavior

[**Watch this on Travis CI**](https://travis-ci.org/Kristinita/SashaGruntDebugging/jobs/365675875#L457-L458):

```markdown
SashaJsBeautify.html
    13:07 ❌️ expected final newline (EditorConfig insert_final_newline https://goo.gl/LRCZMy)
```

`"indent_with_tabs": true,` successful works.

### 6. Expected behavior

**If** `js-beautify -rn SashaJsBeautify.html`:

    final newline successful added.

Thanks.

**Comment by bitwiseman** [comment]
Are you calling this with `--editorconfig` option?  If not, editorconfig is not processed.

**Comment by Kristinita** [comment]
@bitwiseman ,

1. I add information about `.editorconfig` and `eclint` only for demonstrating, that final newline doesn't add. Yes, I'm understood, that `.editorconfig` is not processed, but I need, that `.jsbeautifyrc`, not `.editorconfig` processed correct.
1. In real projects I use [**Grunt wrapper for JsBeautify**](https://www.npmjs.com/package/grunt-jsbeautifier). [**It support `.jsbeautifyrc`**](https://www.npmjs.com/package/grunt-jsbeautifier#optionsconfig-optional), but not `.editorconfig`. So I can not use `--editorconfig` argument in my projects.

Thanks.

**Comment by Kristinita** [comment]
**Status: Outdated issue** 👵

grunt-jsbeautifier [**not updated since 2016**](https://github.com/vkadam/grunt-jsbeautifier/commits/master/). Apparently, its development has been discontinued, and this issue becomes irrelevant. I migrated from grunt-jsbeautifier to js-beautify Node.js CLI.

For js-beautify CLI I get desired behavior if I use the CLI option `--editorconfig` and add `insert_final_newline = true` to my `.editorconfig`.

Thanks.
