### ISSUE TITLE
How do I force consistent newlines?

### ISSUE THREAD

**Issue by adaboese** [beautifier/js-beautify#2231]
# Input
The code looked like this before beautification:

Input (1)

```html
<a href="https://example.com">
  Example <img src="example.png">
</a>
```

Input (2)

```html
<a href="https://example.com">Example <img src="example.png"></a>
```

# Expected Output
The code should have looked like this after beautification:

Any of the following:

```html
<a href="https://example.com">
  Example <img src="example.png">
</a>
```

```html
<a href="https://example.com">Example <img src="example.png"></a>
```

i.e. I am Okay with either of the outputs, as long as both inputs produce the same output.

# Actual Output
The  code actually looked like this after beautification:

Input (1) produces:

```html
<a href="https://example.com"> Example <img src="example.png">
</a>
```

* there is unexpected space before "Example"
* there is unexpected line-break after `<img />`

Input (2) remains as is (good).

# Steps to Reproduce

```ts
format.html_beautify(html, {
  end_with_newline: false,
  indent_body_inner_html: false,
  indent_char: ' ',
  indent_handlebars: false,
  indent_head_inner_html: false,
  indent_inner_html: false,
  indent_size: 2,
  indent_with_tabs: false,
  preserve_newlines: false,
  unformatted: ['code', 'pre', 'em', 'strong', 'span'],
  wrap_attributes: 'force-aligned',
  wrap_line_length: 0,
});
```

**Comment by adaboese** [comment]
Could be related? https://github.com/beautifier/js-beautify/issues/1975

**Comment by adaboese** [comment]
Following this comment, I was able to get rid of the newline

https://github.com/beautifier/js-beautify/issues/2130#issuecomment-1400267006

```diff
- <a href="https://example.com">Example <img src="example.png"></a>
+ <a href="https://example.com"> Example <img src="example.png"> </a>
```

But now I still have the extra space between tags.

@amanmalh do you happen to know how to get rid of the extra space?

**Comment by bitwiseman** [comment]
`preserve_newlines: true` would be a good place to start.

**Comment by adaboese** [comment]
`preserve_newlines` comes with other issues.

```ts
return format.html_beautify(html, {
  content_unformatted: [],
  end_with_newline: false,
  indent_body_inner_html: true,
  indent_char: ' ',
  indent_handlebars: false,
  indent_head_inner_html: false,
  indent_inner_html: true,
  indent_size: 2,
  indent_with_tabs: false,
  inline: [],
  max_preserve_newlines: 0,
  preserve_newlines: true,
  unformatted: [],
  wrap_attributes: 'force-aligned',
  wrap_line_length: 0,
});
```

```ts
it.only('uses consistent indentation (1)', () => {
  expect(
    formatHtml(`
    <a href="https://example.com">
      Example <img src="example.png">
    </a>
  `),
  ).toMatchInlineSnapshot(`
    "<a href="https://example.com">
      Example
      <img src="example.png">
    </a>"
  `);
});

it.only('uses consistent indentation (2)', () => {
  expect(
    formatHtml(`
    <a href="https://example.com">Example <img src="example.png"></a>
  `),
  ).toMatchInlineSnapshot(
    `
    "<a href="https://example.com">Example
      <img src="example.png">
    </a>"
  `,
  );
});
```

Note that the output is not the same.

**Comment by bitwiseman** [comment]
In the original description @adaboese said: 
> i.e. I am Okay with either of the outputs, as long as both inputs produce the same output.

Ah, this looks like another case similar to https://github.com/beautifier/js-beautify/issues/1998#issuecomment-1088275149

The `<a>` tag text contents are are "inline" and thus space-sensitive. The beautifier can't add a space/newline there nor can it remove it.  You have two functionally different inputs, they will always produce at least slightly different outputs (as you noted in your "Actual Outputs").  Sorry.

**Comment by adaboese** [comment]
Feels like it would be nice to have an option that disregards the difference in this case, even if it technically produces output that visually may appear different from the input. My use case requires extracting HTML from DOM and then finding the effectively the same HTML in other documents. I do this by formatting the extracted HTML and every document that I search and then look for literal match.

In this particular case, I was able to achieve what I want by writing a function that searches for HTML within another document while disregarding white space.
